### ISSUE TITLE
Astro + Analog in a NX monorepo

### ISSUE THREAD

**Issue by rujorgensen** [brandonroberts/astro-2-analog#1]
Hi! First of all: I apologize for creating an issue--I was looking to reach out, but didn't find the GitHub discussion pages activated here, I hope you'll bear with me 🙂.

I wanted to integrate Atro with Analog in a larger project, and I needed a solid, working, foundation to start with. So I forked your repo, updated Astro to v3, along with other dependencies, then I added NX, and everything is working well👍.

In a typical NX/Angular monorepo, it's common practice to separate out components into libraries, so I created a library, and re-created the `HelloComponent` there. However I have issues configuring tsconfig/vite--it should be possible, right? Can you point me in the right direction?

Heres my fork: https://github.com/rujorgensen/astro-3-analog-nx

Thanks in advance!

**Comment by rujorgensen** [comment]
Got it to work 🙂. I have to use relative imports though, which I will look at in the future.

**Comment by brandonroberts** [comment]
@rujorgensen Cool. Most likely you need to update the tsconfig.json to be the full path so it knows where the tsconfig path aliases are


```ts
tsconfig: 'apps/frontend/astro/tsconfig.json'
```

**Comment by rujorgensen** [comment]
Thanks for the suggestion 👍. I already have the `tsconfig.json` of the Astro app extending the base configuration of the monorepo ( `tsconfig.base.json`), where the paths are defined, is that what you're referring to? 🙂

[apps/frontend/astro/tsconfig.json](https://github.com/rujorgensen/astro-3-analog-nx/blob/main/apps/frontend/astro/tsconfig.json)
```JSON
{
  "extends": [
    "astro/tsconfigs/strict",
    "../../../tsconfig.base.json"
  ],
}
```

[tsconfig.base.json](https://github.com/rujorgensen/astro-3-analog-nx/blob/main/tsconfig.base.json)
```JSON
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictInputTypes": true,
    "strictTemplates": true
  },
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": [
      "es2020",
      "dom"
    ],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
// 👇 Alias for the component library
      "@frontend/ui/hello": [
        "libs/frontend/ui/src/index.ts"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "tmp"
  ]
}
```

**Comment by brandonroberts** [comment]
Did you get this figured out?

**Comment by rujorgensen** [comment]
Nah 🫤. My knowledge about configuring TypeScript is limited, and the only thing that makes sense in my head is what I posted above. So I'm afraid I'm all out of ideas--I'll likely give it a go again in the future though 🙂.

**Comment by brandonroberts** [comment]
Ok. I'll take another look and respond back here by sometime tomorrow.

**Comment by rujorgensen** [comment]
I've been looking at the issue a little more, and it looks like I might need something like `tsconfigPaths()` (https://www.npmjs.com/package/vite-tsconfig-paths), but adding it to the vite part of the `analogjsangular` config does not seem to have any effect, any thoughs?

![image](https://github.com/brandonroberts/astro-2-analog/assets/6797319/8c0aa4a3-a0a5-49a8-8041-9eda6d4dd691)
